name: 10. Deploy Workload Online 1 

on:
  workflow_dispatch:
    inputs:
      deploy:
        description: 'Deploy after preview'
        #default: false
        type: boolean
      environment:
        description: 'Environment'
        default: "canary"
        required: true
        type: string
      managementGroupPrefix:
        description: 'Management Group Prefix'
        default: "alz"
        required: true
        type: string
      location:
        description: 'Location'
        default: "northeurope"
        type: string
      nva:
        description: 'NVA solution'
        default: 'no-nva'
        type: choice
        options:
          - opnsense-single
          - opnsense-ha
          - no-nva
          - azfirewall-basic
          - ubuntu-single
      vpngw:
        description: 'VPN Gateway'
        default: 'no-vpngw'
        type: choice
        options:
          - vpngw-bgp
          - vpngw-nobgp
          - no-vpngw

  workflow_call:
    inputs:
      deploy:
        description: 'Deploy after preview'
        default: false
        type: boolean
      environment:
        default: "canary"
        required: true
        type: string
      managementGroupPrefix:
        default: "alz"
        required: true
        type: string
      location:
        default: "germanywestcentral"
        type: string
      nva:
        description: 'NVA solution'
        type: string
      vpngw:
        description: 'VPN Gateway type'
        type: string

    secrets:
      WL_OL1_SUB_ID:
        required: false
      AZURE_CLIENT_ID:
        required: false
      AZURE_TENANT_ID:
        required: false
      AZURE_SUBSCRIPTION_ID:
        required: false
      

env:
  groupName: 'compute-admins-workload-online-001-${{ inputs.environment }}'
  workloadSubscriptionId: ${{secrets.WL_OL1_SUB_ID}}
  location: ${{inputs.location}}
  runNumber: ${{ github.run_number }}
  managementGroupSuffix: "-${{inputs.environment}}"
  managementGroupPrefix: ${{inputs.managementGroupPrefix}}



permissions:
  id-token: write
  contents: read
jobs:
  wl_ol1_validation_preview:
    runs-on: ubuntu-latest
    environment: ${{inputs.environment}}
    name: WL-OL1 - Validation and Preview
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          path: 'ALZ-Deploy'
      - name: Checkout Repo bicep-registry-modules
        uses: actions/checkout@v4
        with:
            repository: Azure/bicep-registry-modules
            path: 'bicep-registry-modules'
      - name: Show env
        run: env | sort
      - name: Azure Login with OIDC
        uses: azure/login@v2
        with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Entra ID groups
        id: create_groups
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            if [[ $(az ad group list --query "[?displayName=='${{ env.groupName }}'] | length(@)") -gt 0 ]]; then
              echo "Group ${{ env.groupName }} already exists.";
            else
              echo "Group ${{ env.groupName }} creation skipped because of validation job.";
            fi
      - name: Subscription Vending - Validation
        id: sub_vend_validation
        uses: azure/bicep-deploy@v2
        with:
          type: deployment
          operation: validate
          name: sub_vend_validation-${{ env.runNumber }}
          location: ${{ env.location }}
          scope: managementGroup
          management-group-id: ${{ env.managementGroupPrefix }}${{env.managementGroupSuffix}}
          template-file: ./ALZ-Deploy/infra-as-code/bicep/modules/workload-online1/subvend-workload-online1.bicep
          parameters-file: ./ALZ-Deploy/infra-as-code/bicep/modules/workload-online1/parameters/subvend-workload-online1.parameters.${{inputs.nva}}.${{inputs.vpngw}}.${{inputs.environment}}.json
          parameters: |
            parHubNetworkResourceId: "/subscriptions/c1d4ca0c-0641-4f99-83b8-8a6f2c87a670/resourceGroups/rg-alz-canary-hub-networking-001/providers/Microsoft.Network/virtualNetworks/vnet-gwc-hub-alz-canary"
            parExistingSubscriptionId: "066b4cea-43ad-40d2-a4cc-e5caf5d19e1c"
            parVirtualNetworkDnsServers: '[10.20.1.4]'
            parHubNetworkNvaIpAddress: "10.10.254.4"


  wl_ol1_deployment:
    runs-on: ubuntu-latest
    environment: ${{inputs.environment}}
    name: WL-OL1 - Deployment
    if: ${{ inputs.deploy == true }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          path: 'ALZ-Deploy'
      - name: Checkout Repo bicep-registry-modules
        uses: actions/checkout@v4
        with:
            repository: Azure/bicep-registry-modules
            path: 'bicep-registry-modules'
      - name: Azure Login with OIDC
        uses: azure/login@v2
        with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Entra ID groups
        id: create_groups
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            if [[ $(az ad group list --query "[?displayName=='${{ env.groupName }}'] | length(@)") -gt 0 ]]; then
              echo "Group ${{ env.groupName }} already exists.";
            else
              az ad group create --display-name ${{ env.groupName }} --mail-nickname ${{ env.groupName }};
              echo "Group ${{ env.groupName }} created.";
            fi
      