name: Deploy AMBA to ALZ environment 

on:
  workflow_dispatch:
    inputs:
      environment:
        default: "canary"
        required: true
        type: string
      ambaRelease:
        default: "2024-09-02"
        required: true
        type: string
      managementGroupPrefix:
        default: "alz"
        required: true
        type: string
      location:
        default: "germanywestcentral"
        type: string
      wipeAfterDeploy:
        default: false
        type: boolean

  workflow_call:
    inputs:
      environment:
        default: "canary"
        required: true
        type: string
      ambaRelease:
        default: "2024-09-02"
        required: true
        type: string
      managementGroupPrefix:
        default: "alz"
        required: true
        type: string
      location:
        default: "germanywestcentral"
        type: string
      wipeAfterDeploy:
        default: false
        type: boolean
    secrets:
      MGMT_SUB_ID:
        required: false
      AZURE_CLIENT_ID:
        required: false
      AZURE_TENANT_ID:
        required: false
      AZURE_SUBSCRIPTION_ID:
        required: false
      AMBA_ACTIONGROUP_EMAIL:
        required: false


env:
  ambaRelease: ${{inputs.ambaRelease}}
  ManagementGroupPrefix: ${{inputs.managementGroupPrefix}}
  ManagementGroupSuffix: "-${{inputs.environment}}"
  ManagementSubscriptionId: ${{secrets.MGMT_SUB_ID}}
  Location: ${{inputs.location}}
  runNumber: ${{ github.run_number }}

permissions:
  id-token: write
  contents: read

jobs:
  validate_preview_amba:
    runs-on: ubuntu-latest
    name: Deploy AMBA - Validation and Preview
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Show env
        run: env | sort
      - name: Azure Login with OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Deploy AMBA - Validate
        id: deploy_amba_validation
        shell: bash
        run: |
            az deployment mg validate --template-uri https://raw.githubusercontent.com/Azure/azure-monitor-baseline-alerts/refs/tags/${{ env.ambaRelease }}/patterns/alz/alzArm.json \
            --parameters amba/parameters/alzAmba-${{ env.ambaRelease }}.param.${{inputs.environment}}.json \
            --location ${{ env.Location }} --management-group-id ${{ env.ManagementGroupPrefix }}${{ env.ManagementGroupSuffix }} \
            --parameters managementSubscriptionId=${{env.ManagementSubscriptionId}} --parameters ALZMonitorActionGroupEmail='["${{ secrets.AMBA_ACTIONGROUP_EMAIL }}"]' \
            --name deploy_amba_validation-${{ env.runNumber }} 
      - name: Deploy AMBA - Preview
        id: deploy_amba_preview
        shell: bash
        run: |
            az deployment mg what-if --template-uri https://raw.githubusercontent.com/Azure/azure-monitor-baseline-alerts/refs/tags/${{ env.ambaRelease }}/patterns/alz/alzArm.json \
            --parameters amba/parameters/alzAmba-${{ env.ambaRelease }}.param.${{inputs.environment}}.json \
            --location ${{ env.Location }} --management-group-id ${{ env.ManagementGroupPrefix }}${{ env.ManagementGroupSuffix }} \
            --parameters managementSubscriptionId=${{env.ManagementSubscriptionId}} --parameters ALZMonitorActionGroupEmail='["${{ secrets.AMBA_ACTIONGROUP_EMAIL }}"]' \
            --name deploy_amba_preview-${{ env.runNumber }}
  deploy_amba:
    runs-on: ubuntu-latest
    name: Deploy AMBA - Deployment
    needs: [validate_preview_amba]
    environment: ${{inputs.environment}}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Show env
        run: env | sort
      - name: Azure Login with OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Deploy AMBA - Deployment
        id: deploy_amba_deployment
        shell: bash
        run: |
            az deployment mg create --template-uri https://raw.githubusercontent.com/Azure/azure-monitor-baseline-alerts/refs/tags/${{ env.ambaRelease }}/patterns/alz/alzArm.json \
            --parameters amba/parameters/alzAmba-${{ env.ambaRelease }}.param.${{inputs.environment}}.json \
            --location ${{ env.Location }} --management-group-id ${{ env.ManagementGroupPrefix }}${{ env.ManagementGroupSuffix }} \
            --parameters managementSubscriptionId=${{env.ManagementSubscriptionId}} --parameters ALZMonitorActionGroupEmail='["${{ secrets.AMBA_ACTIONGROUP_EMAIL }}"]' \
            --name deploy_amba_deployment-${{ env.runNumber }} 
  remediate:
    runs-on: ubuntu-latest
    name: Remediate AMBA Policies
    needs: [deploy_amba]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Show env
        run: echo remdiate policies 
     