name: 2. Deploy Onpremise Network Infrastructure

on:
  workflow_dispatch:
    inputs:
      deploy:
        description: 'Deploy after preview'
        #default: false
        type: boolean
      environment:
        default: "canary"
        required: true
        type: string
      location:
        default: "northeurope"
        type: string
      nva:
        description: 'NVA solution'
        type: choice
        options:
          - no-nva
          - opnsense-single
          - opnsense-ha
          - ubuntu-single
          - ubuntu-ha
      vpngw:
        description: 'VPN Gateway'
        default: 'vpngw-nobgp'
        type: choice
        options:
          - vpngw-bgp
          - vpngw-nobgp
          - no-vpngw
      activeDirectory:
        description: 'Active Directory Scenario'
        default: 'create-onprem-domain'
        type: choice
        options:
          - create-onprem-domain
          - no-onprem-domain
      
  workflow_call:
    inputs:
      deploy:
        description: 'Deploy after preview'
        default: false
        type: boolean
      environment:
        default: "canary"
        required: true
        type: string
      location:
        default: "northeurope"
        type: string
      nva:
        description: 'NVA solution'
        type: string
      vpngw:
        description: 'VPN Gateway type'
        type: string
        default: "vpngw-nobgp"
      activeDirectory:
        description: 'Active Directory Scenario'
        default: 'create-onprem-domain'
        type: string
      
    secrets:
      ONPREM_SUB_ID:
        required: false
      AZURE_CLIENT_ID:
        required: false
      AZURE_TENANT_ID:
        required: false
      AZURE_SUBSCRIPTION_ID:
        required: false
      CONNECTIVITY_SUB_ID:
        required: false

env:
  ManagementGroupSuffix: "-${{inputs.environment}}"
  onpremSubscriptionId: ${{secrets.ONPREM_SUB_ID}}
  ConnectivitySubId: ${{ secrets.CONNECTIVITY_SUB_ID }}
  onpremResourceGroupName: "rg-${{inputs.environment}}-onprem"
  HubNetworkResourceGroupName: "rg-alz-${{inputs.environment}}-hub-networking-001"
  Location: ${{inputs.location}}
  runNumber: ${{ github.run_number }}

permissions:
  id-token: write
  contents: read

jobs:
  onprem_validation_preview:
    runs-on: ubuntu-latest
    environment: ${{inputs.environment}}
    name: Onprem - Validation and Preview
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          path: 'ALZ-Deploy'
      - name: Checkout Repo bicep-registry-modules
        uses: actions/checkout@v4
        with:
            repository: Azure/bicep-registry-modules
            path: 'bicep-registry-modules'
      - name: Azure Login with OIDC
        uses: azure/login@v2
        with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Install xmlstarlet
        run: |
          sudo apt-get update
          sudo apt-get -y install xmlstarlet
      - name: Get existing Azure VPN Gateway resources
        if: ${{ inputs.vpngw == 'vpngw-nobgp' || inputs.vpngw == 'vpngw-bgp'  }}        
        id: get_vpngw_resources
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account set -s "${{env.ConnectivitySubId}}"
            publicIpPrefix=$(jq -r .parameters.parPublicIpPrefix.value ./ALZ-Deploy/infra-as-code/bicep/modules/hubNetworking/parameters/hubNetworking.parameters.${{inputs.nva}}.${{inputs.vpngw}}.${{inputs.environment}}.json) 
            vpnGatewayName=$(jq -r .parameters.parVpnGatewayConfig.value.name ./ALZ-Deploy/infra-as-code/bicep/modules/hubNetworking/parameters/hubNetworking.parameters.${{inputs.nva}}.${{inputs.vpngw}}.${{inputs.environment}}.json) 
            publicIpId1=$(az network public-ip list --out tsv --query "[?name=='$publicIpPrefix$vpnGatewayName'].id")
            vpnGatewayIp1=$(az network public-ip show --ids $publicIpId1 --query "ipAddress" --out tsv)
            vpnGwTunnelIp1=$(az network vnet-gateway show -n $vpnGatewayName -g ${{env.HubNetworkResourceGroupName}} --query "bgpSettings.bgpPeeringAddresses[0].tunnelIpAddresses[0]" --output tsv)
            vpnGwTunnelIp2=$(az network vnet-gateway show -n $vpnGatewayName -g ${{env.HubNetworkResourceGroupName}} --query "bgpSettings.bgpPeeringAddresses[1].tunnelIpAddresses[0]" --output tsv)
            vpnGwBgpIp1=$(az network vnet-gateway show -n $vpnGatewayName -g ${{env.HubNetworkResourceGroupName}} --query "bgpSettings.bgpPeeringAddresses[0].defaultBgpIpAddresses"  --output tsv)
            vpnGwBgpIp2=$(az network vnet-gateway show -n $vpnGatewayName -g ${{env.HubNetworkResourceGroupName}} --query "bgpSettings.bgpPeeringAddresses[1].defaultBgpIpAddresses"  --output tsv)
            publicIpId2=$(az network public-ip list --out tsv --query "[?name=='$publicIpPrefix$vpnGatewayName-aa'].id")
            vpnGatewayIp2=$(az network public-ip show --ids $publicIpId2 --query "ipAddress" --out tsv)
            echo "publicIpPrefix: $publicIpPrefix"
            echo "vpnGatewayName: $vpnGatewayName"
            echo "publicIpId1: $publicIpId1"
            echo "vpnGatewayIp1: $vpnGatewayIp1"
            echo "publicIpId2: $publicIpId2"
            echo "vpnGatewayIp2: $vpnGatewayIp2"
            echo "opnSenseName: $opnSenseName"
            echo "vpnGwTunnelIp1: $vpnGwTunnelIp1"
            echo "vpnGwTunnelIp2: $vpnGwTunnelIp2"
            echo "vpnGwBgpIp1: $vpnGwBgpIp1"
            echo "vpnGwBgpIp2: $vpnGwBgpIp2"
            echo "$opnSenseCustomScriptExtensionId"
            echo "publicIpPrefix=$publicIpPrefix" >> "$GITHUB_OUTPUT"
            echo "vpnGatewayName=$vpnGatewayName" >> "$GITHUB_OUTPUT"
            echo "publicIpId1=$publicIpId1" >> "$GITHUB_OUTPUT"
            echo "vpnGatewayIp1=$vpnGatewayIp1" >> "$GITHUB_OUTPUT"
            echo "publicIpId2=$publicIpId2" >> "$GITHUB_OUTPUT"
            echo "vpnGatewayIp2=$vpnGatewayIp1" >> "$GITHUB_OUTPUT"
            echo "vpnGwTunnelIp1=$vpnGwTunnelIp1" >> "$GITHUB_OUTPUT"
            echo "vpnGwTunnelIp2=$vpnGwTunnelIp2" >> "$GITHUB_OUTPUT"
            echo "vpnGwBgpIp1=$vpnGwBgpIp1" >> "$GITHUB_OUTPUT"
            echo "vpnGwBgpIp2=$vpnGwBgpIp2" >> "$GITHUB_OUTPUT"
      # - name: Get existing Azure VPN Gateway resources
      #   if: ${{ inputs.vpngw == 'vpngw-bgp'  }}        
      #   id: get_vpngw_aa_resources
      #   uses: azure/cli@v2
      #   with:
      #     azcliversion: latest
      #     inlineScript: |
      #       az account set -s "${{env.ConnectivitySubId}}"
      #       publicIpPrefix=$(jq -r .parameters.parPublicIpPrefix.value ./ALZ-Deploy/infra-as-code/bicep/modules/hubNetworking/parameters/hubNetworking.parameters.${{inputs.nva}}.${{inputs.vpngw}}.${{inputs.environment}}.json) 
      #       vpnGatewayName=$(jq -r .parameters.parVpnGatewayConfig.value.name ./ALZ-Deploy/infra-as-code/bicep/modules/hubNetworking/parameters/hubNetworking.parameters.${{inputs.nva}}.${{inputs.vpngw}}.${{inputs.environment}}.json) 
      #       publicIpId1=$(az network public-ip list --out tsv --query "[?name=='$publicIpPrefix$vpnGatewayName'].id")
      #       vpnGatewayIp1=$(az network public-ip show --ids $publicIpId1 --query "ipAddress" --out tsv)
      #       publicIpId2=$(az network public-ip list --out tsv --query "[?name=='$publicIpPrefix$vpnGatewayName-aa'].id")
      #       vpnGatewayIp2=$(az network public-ip show --ids $publicIpId2 --query "ipAddress" --out tsv)
      #       echo "$publicIpPrefix"
      #       echo "$vpnGatewayName"
      #       echo "$publicIpId1"
      #       echo "$publicIpId2"
      #       echo "$vpnGatewayIp1"
      #       echo "$vpnGatewayIp2"
      #       echo "$opnSenseName"
      #       echo "$opnSenseCustomScriptExtensionId"
      #       echo "publicIpPrefix=$publicIpPrefix" >> "$GITHUB_OUTPUT"
      #       echo "vpnGatewayName=$vpnGatewayName" >> "$GITHUB_OUTPUT"
      #       echo "publicIpId1=$publicIpId1" >> "$GITHUB_OUTPUT"
      #       echo "publicIpId2=$publicIpId2" >> "$GITHUB_OUTPUT"
      #       echo "vpnGatewayIp1=$vpnGatewayIp1" >> "$GITHUB_OUTPUT"
      #       echo "vpnGatewayIp2=$vpnGatewayIp2" >> "$GITHUB_OUTPUT"
      - name: Onprem RG - Validation
        id: onprem_rg_validation
        uses: azure/arm-deploy@v2
        with:
          scope: subscription
          subscriptionId: ${{ env.onpremSubscriptionId }}
          region: ${{ env.Location }}
          template: ./ALZ-Deploy/infra-as-code/bicep/modules/onprem/onprem-rg.bicep
          parameters: >-
            ./ALZ-Deploy/infra-as-code/bicep/modules/onprem/parameters/onprem-rg.parameters.${{inputs.environment}}.json
            parResourceGroupName=${{ env.onpremResourceGroupName }}
          deploymentName: rg-validate-${{ env.runNumber }}
          failOnStdErr: false
          deploymentMode: Validate
      - name: Check installed OPNsense CustomScript extension
        id: check_installed_opns_extension
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account set -s "${{ env.onpremSubscriptionId }}"
            opnSenseName=$(jq -r .parameters.parOpnsenseName.value ./ALZ-Deploy/infra-as-code/bicep/modules/onprem/parameters/onprem.parameters.${{inputs.vpngw}}.${{inputs.environment}}.json)
            if [[ $(az group exists -n ${{ env.onpremResourceGroupName }}) = true ]];
              then
                if [[ $(az vm list --resource-group ${{ env.onpremResourceGroupName }} --query "[?name=='$opnSenseName'] | length(@)") > 0 ]]; 
                  then 
                    opnSenseCustomScriptExtensionId=$(az vm extension list --out tsv -g ${{ env.onpremResourceGroupName }} --vm-name $opnSenseName --query "[?name=='CustomScript'].id")
                fi  
            fi
            if [ -n "$opnSenseCustomScriptExtensionId" ]; 
              then echo "OPNsense CustomScript Extension already installed"
              echo "install-opnsense=no" >> "$GITHUB_OUTPUT"
            else
              echo "OPNsense CustomScript Extension not installed"
              echo "install-opnsense=yes" >> "$GITHUB_OUTPUT"
            fi
            echo "opnSenseCustomScriptExtensionId=$opnSenseCustomScriptExtensionId" >> "$GITHUB_OUTPUT"
            echo "opnSenseCustomScriptExtensionId=$opnSenseCustomScriptExtensionId"
      - name: Onprem - Validation
        id: onprem_validation
        uses: azure/arm-deploy@v2
        with:
          scope: subscription
          subscriptionId: ${{ env.onpremSubscriptionId }}
          region: ${{ env.Location }}
          template: ./ALZ-Deploy/infra-as-code/bicep/modules/onprem/onprem.bicep
          parameters: >-
            ./ALZ-Deploy/infra-as-code/bicep/modules/onprem/parameters/onprem.parameters.${{inputs.vpngw}}.${{inputs.environment}}.json
            parResourceGroupName=${{ env.onpremResourceGroupName }}
            parVpnGwPublicIp1=${{ steps.get_vpngw_resources.outputs.vpnGatewayIp}}
            parInstallOpnsense=${{steps.check_installed_opns_extension.outputs.install-opnsense}}
            parActiveDirectoryScenario=${{inputs.activeDirectory}}
          deploymentName: onprem-validate-${{ env.runNumber }}
          failOnStdErr: false
          deploymentMode: Validate
      - name: Onprem RG - Preview
        id: onprem_rg_preview
        uses: azure/arm-deploy@v2
        with:
          scope: subscription
          subscriptionId: ${{ env.onpremSubscriptionId }}
          region: ${{ env.Location }}
          template: ./ALZ-Deploy/infra-as-code/bicep/modules/onprem/onprem-rg.bicep
          parameters: >-
            ./ALZ-Deploy/infra-as-code/bicep/modules/onprem/parameters/onprem-rg.parameters.${{inputs.environment}}.json
            parResourceGroupName=${{ env.onpremResourceGroupName }}
          deploymentName: rg-preview-${{ env.runNumber }}
          failOnStdErr: false
          additionalArguments: "--what-if"
      - name: Onprem - Preview
        id: onprem_preview
        uses: azure/arm-deploy@v2
        with:
          scope: subscription
          subscriptionId: ${{ env.onpremSubscriptionId }}
          region: ${{ env.Location }}
          template: ./ALZ-Deploy/infra-as-code/bicep/modules/onprem/onprem.bicep
          parameters: >-
            ./ALZ-Deploy/infra-as-code/bicep/modules/onprem/parameters/onprem.parameters.${{inputs.vpngw}}.${{inputs.environment}}.json
            parResourceGroupName=${{ env.onpremResourceGroupName }}
            parVpnGwPublicIp1=${{ steps.get_vpngw_resources.outputs.vpnGatewayIp}}
            parInstallOpnsense=${{steps.check_installed_opns_extension.outputs.install-opnsense}}
            parActiveDirectoryScenario=${{inputs.activeDirectory}}
          deploymentName: onprem-preview-${{ env.runNumber }}
          failOnStdErr: false
          additionalArguments: "--what-if"
  onprem_deployment:
    if: ${{ inputs.deploy && (needs.onprem_validation_preview.result == 'skipped' || needs.onprem_validation_preview.result == 'success')}}
    # if: ${{ inputs.deploy && (needs.onprem_validation_preview.result == 'skipped')}}
    needs:
      - onprem_validation_preview
    runs-on: ubuntu-latest
    environment: ${{inputs.environment}}
    name: Onprem - Deployment
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
      with:
          path: 'ALZ-Deploy'
    - name: Checkout Repo bicep-registry-modules
      uses: actions/checkout@v4
      with:
          repository: Azure/bicep-registry-modules
          path: 'bicep-registry-modules'
    - name: Azure Login with OIDC
      uses: azure/login@v2
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - name: Install xmlstarlet
      run: |
        sudo apt-get update
        sudo apt-get -y install xmlstarlet
    - name: Get existing Azure VPN Gateway resources
      if: ${{ inputs.vpngw == 'vpngw-nobgp' || inputs.vpngw == 'vpngw-bgp'  }}    
      id: get_vpngw_resources
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az account set -s "${{env.ConnectivitySubId}}"
          publicIpPrefix=$(jq -r .parameters.parPublicIpPrefix.value ./ALZ-Deploy/infra-as-code/bicep/modules/hubNetworking/parameters/hubNetworking.parameters.${{inputs.nva}}.${{inputs.vpngw}}.${{inputs.environment}}.json) 
          vpnGatewayName=$(jq -r .parameters.parVpnGatewayConfig.value.name ./ALZ-Deploy/infra-as-code/bicep/modules/hubNetworking/parameters/hubNetworking.parameters.${{inputs.nva}}.${{inputs.vpngw}}.${{inputs.environment}}.json) 
          publicIpId1=$(az network public-ip list --out tsv --query "[?name=='$publicIpPrefix$vpnGatewayName'].id")
          vpnGatewayIp1=$(az network public-ip show --ids $publicIpId1 --query "ipAddress" --out tsv)
          echo "$publicIpPrefix"
          echo "$vpnGatewayName"
          echo "$publicIpId"
          echo "$vpnGatewayIp1"
          echo "publicIpPrefix=$publicIpPrefix" >> "$GITHUB_OUTPUT"
          echo "vpnGatewayName=$vpnGatewayName" >> "$GITHUB_OUTPUT"
          echo "publicIpId1=$publicIpId1" >> "$GITHUB_OUTPUT"
          echo "vpnGatewayIp1=$vpnGatewayIp1" >> "$GITHUB_OUTPUT"
    - name: Onprem RG - Deployment
      id: onprem_rg_deploy
      uses: azure/arm-deploy@v2
      with:
        scope: subscription
        subscriptionId: ${{ env.onpremSubscriptionId }}
        region: ${{ env.Location }}
        template: ./ALZ-Deploy/infra-as-code/bicep/modules/onprem/onprem-rg.bicep
        parameters: >-
          ./ALZ-Deploy/infra-as-code/bicep/modules/onprem/parameters/onprem-rg.parameters.${{inputs.environment}}.json
          parResourceGroupName=${{ env.onpremResourceGroupName }}
        deploymentName: rg-deploy-${{ env.runNumber }}
        failOnStdErr: false
    - name: Check installed OPNsense CustomScript extension
      id: check_installed_opns_extension
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az account set -s "${{ env.onpremSubscriptionId }}"
          opnSenseName=$(jq -r .parameters.parOpnsenseName.value ./ALZ-Deploy/infra-as-code/bicep/modules/onprem/parameters/onprem.parameters.${{inputs.vpngw}}.${{inputs.environment}}.json)
          if [[ $(az group exists -n ${{ env.onpremResourceGroupName }}) = true ]];
            then
              if [[ $(az vm list --resource-group ${{ env.onpremResourceGroupName }} --query "[?name=='$opnSenseName'] | length(@)") > 0 ]]; 
                then 
                  opnSenseCustomScriptExtensionId=$(az vm extension list --out tsv -g ${{ env.onpremResourceGroupName }} --vm-name $opnSenseName --query "[?name=='CustomScript'].id")
              fi  
          fi
          if [ -n "$opnSenseCustomScriptExtensionId" ]; 
            then echo "OPNsense CustomScript Extension already installed"
            echo "install-opnsense=no" >> "$GITHUB_OUTPUT"
          else
            echo "OPNsense CustomScript Extension not installed"
            echo "install-opnsense=yes" >> "$GITHUB_OUTPUT"
          fi
          echo "opnSenseCustomScriptExtensionId=$opnSenseCustomScriptExtensionId" >> "$GITHUB_OUTPUT"
          echo "opnSenseCustomScriptExtensionId=$opnSenseCustomScriptExtensionId"
    - name: Onprem - Deployment
      id: onprem_deployment
      uses: azure/arm-deploy@v2
      with:
        scope: subscription
        subscriptionId: ${{ env.onpremSubscriptionId }}
        region: ${{ env.Location }}
        template: ./ALZ-Deploy/infra-as-code/bicep/modules/onprem/onprem.bicep
        parameters: >-
          ./ALZ-Deploy/infra-as-code/bicep/modules/onprem/parameters/onprem.parameters.${{inputs.vpngw}}.${{inputs.environment}}.json
          parResourceGroupName=${{ env.onpremResourceGroupName }}
          parVpnGwPublicIp1=${{ steps.get_vpngw_resources.outputs.vpnGatewayIp}}
          parInstallOpnsense=${{steps.check_installed_opns_extension.outputs.install-opnsense}}
          parActiveDirectoryScenario=${{inputs.activeDirectory}}
        deploymentName: onprem-deploy-${{ env.runNumber }}
        failOnStdErr: false
    




