name: ALZ Bicep deployment pipeline

on:
  push:
    branches:
      - main
    #paths:
    #  - ".github/workflows/deploy-alz.yml"
  workflow_dispatch: {}
env:
  alzBicepRelease: "v0.19.4"
  ManagementGroupPrefix: "alz-bicep"
  ManagementGroupSuffix: "-prod"
  TopLevelManagementGroupDisplayName: "ALZ-Bicep-Prod"
  Location: "germanywestcentral"
  LoggingSubId: ${{ secrets.LOGGING_SUB_ID }}
  IdentitySubId: ${{ secrets.IDENTITY_SUB_ID }}
  LoggingResourceGroupName: "rg-alz-bicep-prod-logging-001"
  MgmtSubId: ${{ secrets.MGMT_SUB_ID }}
  ConnectivitySubId: ${{ secrets.CONNECTIVITY_SUB_ID }}
  HubNetworkResourceGroupName: "rg-alz-bicep-prod-hub-networking-001"
  RoleAssignmentManagementGroupId: "alz-bicep-platform-prod"
  DefenderForCloudEmailSecurityContact: ${{ secrets.DFC_EMAIL_SECURITY_CONTACT }}
  SpokeNetworkSubId: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
  SpokeNetworkResourceGroupName: "Spoke_Networking_POC"
  runNumber: ${{ github.run_number }}

permissions:
  id-token: write
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Run lint job
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          path: main
      - name: Checkout ALZ-Bicep Repo
        uses: actions/checkout@v4
        with:
          repository: Azure/ALZ-Bicep
          path: ALZ-Bicep
          ref: ${{ env.alzBicepRelease }}
      - name: Azure Login with OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Run bicep linter
        run: |
          az bicep build --file ALZ-Bicep/infra-as-code/bicep/modules/managementGroups/managementGroups.bicep
          # az bicep build --file infra-as-code/bicep/modules/policy/definitions/customPolicyDefinitions.bicep
          # az bicep build --file infra-as-code/bicep/modules/customRoleDefinitions/customRoleDefinitions.bicep
          # az bicep build --file infra-as-code/bicep/modules/resourceGroup/resourceGroup.bicep
          # az bicep build --file infra-as-code/bicep/modules/logging/logging.bicep
          # az bicep build --file infra-as-code/bicep/orchestration/mgDiagSettingsAll/mgDiagSettingsAll.bicep
          # az bicep build --file infra-as-code/bicep/modules/resourceGroup/resourceGroup.bicep
          # az bicep build --file infra-as-code/bicep/modules/hubNetworking/hubNetworking.bicep
          # az bicep build --file infra-as-code/bicep/orchestration/subPlacementAll/subPlacementAll.bicep
  validate:
    runs-on: ubuntu-latest
    needs: [lint]
    name: Run validation job
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          path: main
      - name: Checkout ALZ-Bicep Repo
        uses: actions/checkout@v4
        with:
          repository: Azure/ALZ-Bicep
          path: ALZ-Bicep
          ref: ${{ env.alzBicepRelease }}
      - name: Azure Login with OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Validate Deployment
        id: validate
        shell: bash
        run: |
          az deployment tenant validate --template-file ./main/deploy/main.bicep \
          --parameters parTopLevelManagementGroupPrefix=${{ env.ManagementGroupPrefix }} \
          --parameters parTopLevelManagementGroupSuffix=${{ env.ManagementGroupSuffix }} \
          --parameters parTopLevelManagementGroupDisplayName="${{ env.TopLevelManagementGroupDisplayName }}" \
          --parameters parLoggingSubscriptionId="${{ env.LoggingSubId }}" \
          --parameters parLoggingResourceGroupName="${{ env.LoggingResourceGroupName }}" \
          --parameters parConnectivitySubscriptionId=${{ env.ConnectivitySubId }} \
          --parameters parHubNetworkResourceGroupName="${{ env.HubNetworkResourceGroupName }}" \
          --parameters parMgmtSubscriptionId=${{ env.MgmtSubId}} \
          --parameters parIdentitySubscriptionId=${{ env.IdentitySubId}} \
          --location ${{ env.Location }} --name alz-deployment-${{ env.runNumber }}
  preview:
    runs-on: ubuntu-latest
    needs: [validate]
    name: Run preview job
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          path: main
      - name: Checkout ALZ-Bicep Repo
        uses: actions/checkout@v4
        with:
          repository: Azure/ALZ-Bicep
          path: ALZ-Bicep
          ref: ${{ env.alzBicepRelease }}
      - name: Azure Login with OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Preview Deployment
        id: preview
        shell: bash
        run: |
          az deployment tenant what-if --template-file ./main/deploy/main.bicep \
          --parameters parTopLevelManagementGroupPrefix=${{ env.ManagementGroupPrefix }} \
          --parameters parTopLevelManagementGroupSuffix=${{ env.ManagementGroupSuffix }} \
          --parameters parTopLevelManagementGroupDisplayName="${{ env.TopLevelManagementGroupDisplayName }}" \
          --parameters parLoggingSubscriptionId=${{ env.LoggingSubId }} \
          --parameters parLoggingResourceGroupName="${{ env.LoggingResourceGroupName }}" \
          --parameters parConnectivitySubscriptionId=${{ env.ConnectivitySubId }} \
          --parameters parHubNetworkResourceGroupName="${{ env.HubNetworkResourceGroupName}}" \
          --parameters parMgmtSubscriptionId=${{ env.MgmtSubId}} \
          --parameters parIdentitySubscriptionId=${{ env.IdentitySubId}} \
          --location ${{ env.Location }} --name alz-deployment-${{ env.runNumber }}
  deploy:
    runs-on: ubuntu-latest
    needs: [preview]
    environment: deploy
    name: Run deploy job
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          path: main
      - name: Checkout ALZ-Bicep Repo
        uses: actions/checkout@v4
        with:
          repository: Azure/ALZ-Bicep
          path: ALZ-Bicep
          ref: ${{ env.alzBicepRelease }}
      - name: Azure Login with OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      # - name: Preview Deployment
      #   id: preview
      #   shell: bash
      #   run: |
      #     az deployment tenant create --template-file ./main/deploy/main.bicep \
      #     --parameters parTopLevelManagementGroupPrefix=${{ env.ManagementGroupPrefix }} \
      #     --parameters parTopLevelManagementGroupSuffix=${{ env.ManagementGroupSuffix }} \
      #     --parameters parTopLevelManagementGroupDisplayName="${{ env.TopLevelManagementGroupDisplayName }}" \
      #     --location ${{ env.Location }} --name alz-deployment-${{ env.runNumber }}


