name: 3. Deploy NVA OpnSense HA to ALZ environment 

on:
  workflow_dispatch:
    inputs:
      deploy:
        description: 'Deploy after preview'
        default: false
        type: boolean
      environment:
        default: "canary"
        required: true
        type: string
      managementGroupPrefix:
        default: "alz"
        required: true
        type: string
      vpngw:
        description: 'VPN Gateway'
        default: 'no-vpngw'
        type: choice
        options:
          - vpngw-bgp
          - vpngw-nobgp
          - no-vpngw
      location:
        default: "germanywestcentral"
        type: string
      wipeAfterDeploy:
        default: false
        type: boolean

  workflow_call:
    inputs:
      deploy:
        description: 'Deploy after preview'
        default: false
        type: boolean
      environment:
        default: "canary"
        required: true
        type: string
      managementGroupPrefix:
        default: "alz"
        required: true
        type: string
      vpngw:
        description: 'VPN Gateway type'
        type: string
        default: "vpngw-nobgp"
      location:
        default: "germanywestcentral"
        type: string
      wipeAfterDeploy:
        default: false
        type: boolean
    secrets:
      CONNECTIVITY_SUB_ID:
        required: false
      AZURE_CLIENT_ID:
        required: false
      AZURE_TENANT_ID:
        required: false
      AZURE_SUBSCRIPTION_ID:
        required: false
env:
  ManagementGroupPrefix: ${{inputs.managementGroupPrefix}}
  ManagementGroupSuffix: "-${{inputs.environment}}"
  ConnectivitySubscriptionId: ${{secrets.CONNECTIVITY_SUB_ID}}
  hubNetworkResourceGroupName: "rg-${{inputs.managementGroupPrefix}}-${{inputs.environment}}-hub-networking-001"
  Location: ${{inputs.location}}
  runNumber: ${{ github.run_number }}

permissions:
  id-token: write
  contents: read

jobs:
  validate_preview_opns:
    runs-on: ubuntu-latest
    environment: ${{inputs.environment}}
    name: Deploy NVA OpnSense HA - Validation and Preview
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
      with:
        path: 'ALZ-Deploy'
    - name: Checkout Repo bicep-registry-modules
      uses: actions/checkout@v4
      with:
          repository: Azure/bicep-registry-modules
          path: 'bicep-registry-modules'
    - name: Azure Login with OIDC
      uses: azure/login@v2
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - name: Get existing resources
      id: get_resources
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az account set -s "${{env.ConnectivitySubscriptionId}}"
          hubNetworkName=$(jq -r .parameters.parHubNetworkName.value ./ALZ-Deploy/infra-as-code/bicep/modules/hubNetworking/parameters/hubNetworking.parameters.opnsense-single.${{inputs.vpngw}}.${{inputs.environment}}.json) 
          hubNetworkResourceId=$(az network vnet show --resource-group ${{ env.hubNetworkResourceGroupName }} --name $hubNetworkName --query id)
          echo "$hubNetworkResourceId"
          echo "hubNetworkResourceId=$hubNetworkResourceId" >> $GITHUB_OUTPUT
    - name: Check installed OPNsense CustomScript extension
      id: check_installed_opns_extension
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az account set -s "${{env.ConnectivitySubscriptionId}}"
            opnSensePrimaryName=$(jq -r .parameters.parPrimaryVirtualMachineName.value ./ALZ-Deploy/infra-as-code/bicep/modules/opnsense/parameters/opnsense-ha.parameters.${{inputs.environment}}.json)
            if [[ $(az group exists -n ${{ env.hubNetworkResourceGroupName }}) = true ]];
              then
                if [[ $(az vm list --resource-group ${{ env.hubNetworkResourceGroupName }} --query "[?name=='$opnSensePrimaryName'] | length(@)") > 0 ]]; 
                  then 
                    opnSensePrimaryCustomScriptExtensionId=$(az vm extension list --out tsv -g ${{ env.hubNetworkResourceGroupName }} --vm-name $opnSensePrimaryName --query "[?name=='CustomScript'].id")
                fi  
            fi
            if [ -n "$opnSensePrimaryCustomScriptExtensionId" ]; 
              then echo "OPNsense CustomScript Extension on Primary already installed"
              echo "install-opnsense-primary=no" >> "$GITHUB_OUTPUT"
            else
              echo "OPNsense CustomScript Extension on Primary not installed"
              echo "install-opnsense-primary=yes" >> "$GITHUB_OUTPUT"
            fi
            echo "opnSensePrimaryCustomScriptExtensionId=$opnSensePrimaryCustomScriptExtensionId" >> "$GITHUB_OUTPUT"
            echo "opnSensePrimaryCustomScriptExtensionId=$opnSensePrimaryCustomScriptExtensionId"
            opnSenseSecondaryName=$(jq -r .parameters.parSecondaryVirtualMachineName.value ./ALZ-Deploy/infra-as-code/bicep/modules/opnsense/parameters/opnsense-ha.parameters.${{inputs.environment}}.json)
            if [[ $(az group exists -n ${{ env.hubNetworkResourceGroupName }}) = true ]];
              then
                if [[ $(az vm list --resource-group ${{ env.hubNetworkResourceGroupName }} --query "[?name=='$opnSenseSecondaryName'] | length(@)") > 0 ]]; 
                  then 
                    opnSenseSecondaryCustomScriptExtensionId=$(az vm extension list --out tsv -g ${{ env.hubNetworkResourceGroupName }} --vm-name $opnSenseSecondaryName --query "[?name=='CustomScript'].id")
                fi  
            fi
            if [ -n "$opnSenseSecondaryCustomScriptExtensionId" ]; 
              then echo "OPNsense CustomScript Extension on Secondary already installed"
              echo "install-opnsense-seondary=no" >> "$GITHUB_OUTPUT"
            else
              echo "OPNsense CustomScript Extension on Secondary not installed"
              echo "install-opnsense-secondary=yes" >> "$GITHUB_OUTPUT"
            fi
            echo "opnSenseSecondaryCustomScriptExtensionId=$opnSenseSecondaryCustomScriptExtensionId" >> "$GITHUB_OUTPUT"
            echo "opnSensePrimaryCustomScriptExtensionId=$opnSenseSecondaryCustomScriptExtensionId"
    - name: Deploy NVA OpnSense - Validation
      id: deploy_opns_validation
      uses: azure/arm-deploy@v2
      with:
          scope: resourcegroup
          subscriptionId: ${{ env.ConnectivitySubscriptionId }}
          region: ${{ env.Location }}
          resourceGroupName: ${{ env.hubNetworkResourceGroupName }}
          template: ./ALZ-Deploy/infra-as-code/bicep/modules/opnsense/opnsense-ha.bicep
          parameters: >-
            ./ALZ-Deploy/infra-as-code/bicep/modules/opnsense/parameters/opnsense-ha.parameters.${{inputs.environment}}.json
            parVirtualNetworkResourceId=${{steps.get_resources.outputs.hubNetworkResourceId}}
            parInstallOpnsensePrimary=${{steps.check_installed_opns_extension.outputs.install-opnsense-primary}}
            parInstallOpnsenseSecondary=${{steps.check_installed_opns_extension.outputs.install-opnsense-secondary}}
          deploymentName: deploy_opnsense_validation-${{ env.runNumber }}
          failOnStdErr: false
          deploymentMode: Validate
    - name: Deploy NVA OpnSense - Preview
      id: deploy_opns_preview
      uses: azure/arm-deploy@v2
      with:
          scope: resourcegroup
          subscriptionId: ${{ env.ConnectivitySubscriptionId }}
          region: ${{ env.Location }}
          resourceGroupName: ${{ env.hubNetworkResourceGroupName }}
          template: ./ALZ-Deploy/infra-as-code/bicep/modules/opnsense/opnsense.bicep
          parameters: >-
            ./ALZ-Deploy/infra-as-code/bicep/modules/opnsense/parameters/opnsense.parameters.${{inputs.environment}}.json
            parVirtualNetworkResourceId=${{steps.get_resources.outputs.hubNetworkResourceId}}
            parInstallOpnsensePrimary=${{steps.check_installed_opns_extension.outputs.install-opnsense-primary}}
            parInstallOpnsenseSecondary=${{steps.check_installed_opns_extension.outputs.install-opnsense-secondary}}
          deploymentName: deploy_opnsense_preview-${{ env.runNumber }}
          failOnStdErr: false
          additionalArguments: "--what-if"
  deploy_opns:
    needs:
      - validate_preview_opns
    runs-on: ubuntu-latest
    environment: ${{inputs.environment}}
    name: Deploy NVA OpnSense
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
      with:
        path: 'ALZ-Deploy'
    - name: Checkout Repo bicep-registry-modules
      uses: actions/checkout@v4
      with:
          repository: Azure/bicep-registry-modules
          path: 'bicep-registry-modules'
    - name: Azure Login with OIDC
      uses: azure/login@v2
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - name: Get existing resources
      id: get_resources
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az account set -s "${{env.ConnectivitySubscriptionId}}"
          hubNetworkName=$(jq -r .parameters.parHubNetworkName.value ./ALZ-Deploy/infra-as-code/bicep/modules/hubNetworking/parameters/hubNetworking.parameters.opnsense-single.${{inputs.vpngw}}.${{inputs.environment}}.json)
          hubNetworkResourceId=$(az network vnet show --resource-group ${{ env.hubNetworkResourceGroupName }} --name $hubNetworkName --query id)
          echo "$hubNetworkResourceId"
          echo "hubNetworkResourceId=$hubNetworkResourceId" >> $GITHUB_OUTPUT
    - name: Check installed OPNsense CustomScript extension
      id: check_installed_opns_extension
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az account set -s "${{env.ConnectivitySubscriptionId}}"
            opnSensePrimaryName=$(jq -r .parameters.parPrimaryVirtualMachineName.value ./ALZ-Deploy/infra-as-code/bicep/modules/opnsense/parameters/opnsense-ha.parameters.${{inputs.environment}}.json)
            if [[ $(az group exists -n ${{ env.hubNetworkResourceGroupName }}) = true ]];
              then
                if [[ $(az vm list --resource-group ${{ env.hubNetworkResourceGroupName }} --query "[?name=='$opnSensePrimaryName'] | length(@)") > 0 ]]; 
                  then 
                    opnSensePrimaryCustomScriptExtensionId=$(az vm extension list --out tsv -g ${{ env.hubNetworkResourceGroupName }} --vm-name $opnSensePrimaryName --query "[?name=='CustomScript'].id")
                fi  
            fi
            if [ -n "$opnSensePrimaryCustomScriptExtensionId" ]; 
              then echo "OPNsense CustomScript Extension on Primary already installed"
              echo "install-opnsense-primary=no" >> "$GITHUB_OUTPUT"
            else
              echo "OPNsense CustomScript Extension on Primary not installed"
              echo "install-opnsense-primary=yes" >> "$GITHUB_OUTPUT"
            fi
            echo "opnSensePrimaryCustomScriptExtensionId=$opnSensePrimaryCustomScriptExtensionId" >> "$GITHUB_OUTPUT"
            echo "opnSensePrimaryCustomScriptExtensionId=$opnSensePrimaryCustomScriptExtensionId"
            opnSenseSecondaryName=$(jq -r .parameters.parSecondaryVirtualMachineName.value ./ALZ-Deploy/infra-as-code/bicep/modules/opnsense/parameters/opnsense-ha.parameters.${{inputs.environment}}.json)
            if [[ $(az group exists -n ${{ env.hubNetworkResourceGroupName }}) = true ]];
              then
                if [[ $(az vm list --resource-group ${{ env.hubNetworkResourceGroupName }} --query "[?name=='$opnSenseSecondaryName'] | length(@)") > 0 ]]; 
                  then 
                    opnSenseSecondaryCustomScriptExtensionId=$(az vm extension list --out tsv -g ${{ env.hubNetworkResourceGroupName }} --vm-name $opnSenseSecondaryName --query "[?name=='CustomScript'].id")
                fi  
            fi
            if [ -n "$opnSenseSecondaryCustomScriptExtensionId" ]; 
              then echo "OPNsense CustomScript Extension on Secondary already installed"
              echo "install-opnsense-seondary=no" >> "$GITHUB_OUTPUT"
            else
              echo "OPNsense CustomScript Extension on Secondary not installed"
              echo "install-opnsense-secondary=yes" >> "$GITHUB_OUTPUT"
            fi
            echo "opnSenseSecondaryCustomScriptExtensionId=$opnSenseSecondaryCustomScriptExtensionId" >> "$GITHUB_OUTPUT"
            echo "opnSensePrimaryCustomScriptExtensionId=$opnSenseSecondaryCustomScriptExtensionId"
    - name: Deploy NVA OpnSense
      id: deploy_opns
      uses: azure/arm-deploy@v2
      with:
          scope: resourcegroup
          subscriptionId: ${{ env.ConnectivitySubscriptionId }}
          region: ${{ env.Location }}
          resourceGroupName: ${{ env.hubNetworkResourceGroupName }}
          template: ./ALZ-Deploy/infra-as-code/bicep/modules/opnsense/opnsense.bicep
          parameters: >-
            ./ALZ-Deploy/infra-as-code/bicep/modules/opnsense/parameters/opnsense.parameters.${{inputs.environment}}.json
            parVirtualNetworkResourceId=${{steps.get_resources.outputs.hubNetworkResourceId}}
            parInstallOpnsensePrimary=${{steps.check_installed_opns_extension.outputs.install-opnsense-primary}}
            parInstallOpnsenseSecondary=${{steps.check_installed_opns_extension.outputs.install-opnsense-secondary}}
          deploymentName: deploy_opnsense-${{ env.runNumber }}
          failOnStdErr: false
         