name: 10a. Deploy Workload Online 1 - Application Team

on:
  workflow_dispatch:
    inputs:
      deploy:
        description: 'Deploy after preview'
        #default: false
        type: boolean
      environment:
        description: 'Environment'
        default: "canary"
        required: true
        type: string
      location:
        description: 'Location'
        default: "germanywestcentral"
        type: string
      nva:
        description: 'NVA solution'
        default: 'no-nva'
        type: choice
        options:
          - opnsense-single
          - opnsense-ha
          - no-nva
          - azfirewall-basic
          - ubuntu-single
      vpngw:
        description: 'VPN Gateway'
        default: 'no-vpngw'
        type: choice
        options:
          - vpngw-bgp
          - vpngw-nobgp
          - no-vpngw
      vnetrg:
        description: 'Spoke VNet Resource Group'
        type: string
        default: 'rg-alz-workload-online-001-spoke-gwc'
      vnetname:
        description: 'Spoke VNet Name'
        type: string
        default: 'vnet-gwc-workload-online-001'



  workflow_call:
    inputs:
      deploy:
        description: 'Deploy after preview'
        default: false
        type: boolean
      environment:
        default: "canary"
        required: true
        type: string
      location:
        default: "germanywestcentral"
        type: string
      nva:
        description: 'NVA solution'
        type: string
      vpngw:
        description: 'VPN Gateway type'
        type: string
      vnetrg:
        description: 'Spoke VNet Resource Group'
        type: string
        default: 'rg-alz-workload-online-001-spoke-gwc'
      vnetname:
        description: 'Spoke VNet Name'
        type: string
        default: 'vnet-gwc-workload-online-001'

    secrets:
      WL_OL1_SUB_ID:
        required: false
      AZURE_CLIENT_ID:
        required: false
      AZURE_TENANT_ID:
        required: false
      AZURE_SUBSCRIPTION_ID:
        required: false
      

env:
  workloadSubscriptionId: ${{secrets.WL_OL1_SUB_ID}}
  location: ${{inputs.location}}
  runNumber: ${{ github.run_number }}
  vnetName: '${{inputs.vnetname}}-${{inputs.environment}}'
  vnetRg: '${{inputs.vnetrg}}-${{inputs.environment}}'
  appRgName: 'rg-alz-workload-online-001-compute-gwc-${{inputs.environment}}'



permissions:
  id-token: write
  contents: read

jobs:
  validate_preview_compute_rg:
    runs-on: ubuntu-latest
    name: Compute Resource Group - Validation and Preview
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          path: 'ALZ-Deploy'
      - name: Checkout Repo bicep-registry-modules
        uses: actions/checkout@v4
        with:
            repository: Azure/bicep-registry-modules
            path: 'bicep-registry-modules'
      - name: Show env
        run: env | sort
      - name: Azure Login with OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Compute RG - Validation
        id: compute_rg_validate
        uses: azure/bicep-deploy@v2
        with:
          type: deployment
          operation: validate
          name: compute_rg_validate-${{env.runNumber}}
          location: ${{ env.location }}
          scope: subscription
          subscription-id: ${{secrets.WL_OL1_SUB_ID}}
          template-file: ./bicep-registry-modules/avm/res/resources/resource-group/main.bicep
          parameters-file: ./ALZ-Deploy/workloads/workload-online1/parameters/rg-compute-workload-online1.parameters.${{inputs.environment}}.json
      - name: Compute RG - Preview
        id: compute_rg_preview
        uses: azure/bicep-deploy@v2
        with:
          type: deployment
          operation: whatIf
          name: compute_rg_preview-${{env.runNumber}}
          location: ${{ env.location }}
          scope: subscription
          subscription-id: ${{secrets.WL_OL1_SUB_ID}}
          template-file: ./bicep-registry-modules/avm/res/resources/resource-group/main.bicep
          parameters-file: ./ALZ-Deploy/workloads/workload-online1/parameters/rg-compute-workload-online1.parameters.${{inputs.environment}}.json
  deploy_compute_rg:
    runs-on: ubuntu-latest
    needs: validate_preview_compute_rg
    name: Compute Resource Group - Deploy
    if: ${{ inputs.deploy == true }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          path: 'ALZ-Deploy'
      - name: Checkout Repo bicep-registry-modules
        uses: actions/checkout@v4
        with:
            repository: Azure/bicep-registry-modules
            path: 'bicep-registry-modules'
      - name: Show env
        run: env | sort
      - name: Azure Login with OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Compute RG - Deploy
        id: compute_rg_deploy
        uses: azure/bicep-deploy@v2
        with:
          type: deployment
          operation: create
          name: compute_rg_deploy-${{env.runNumber}}
          location: ${{ env.location }}
          scope: subscription
          subscription-id: ${{secrets.WL_OL1_SUB_ID}}
          template-file: ./bicep-registry-modules/avm/res/resources/resource-group/main.bicep
          parameters-file: ./ALZ-Deploy/workloads/workload-online1/parameters/rg-compute-workload-online1.parameters.${{inputs.environment}}.json
          parameters: |
            name: ${{ env.appRgName }}
            location: ${{ env.location }}
  wl_ol1_app_validation_preview:
    runs-on: ubuntu-latest
    needs: deploy_compute_rg
    environment: ${{inputs.environment}}
    name: WL-OL1 Application - Validation and Preview
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          path: 'ALZ-Deploy'
      - name: Checkout Repo bicep-registry-modules
        uses: actions/checkout@v4
        with:
            repository: Azure/bicep-registry-modules
            path: 'bicep-registry-modules'
      - name: Show env
        run: env | sort
      - name: Azure Login with OIDC
        uses: azure/login@v2
        with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Application - Validate
        id: application_validate
        uses: azure/bicep-deploy@v2
        with:
          type: deployment
          operation: validate
          name: application_validate-${{env.runNumber}}
          scope: resourceGroup
          subscription-id: ${{secrets.WL_OL1_SUB_ID}}
          resource-group-name: ${{ env.appRgName }}
          template-file: ./ALZ-Deploy/workloads/workload-online1/main.bicep
          parameters-file: ./ALZ-Deploy/workloads/workload-online1/parameters/workload-online1.parameters.${{inputs.environment}}.json
          parameters: |
            parVnetResourceId: '/subscriptions/${{secrets.WL_OL1_SUB_ID}}/resourceGroups/${{inputs.vnetrg}}/providers/Microsoft.Network/virtualNetworks/${{inputs.vnetrg}}'
      - name: Application - Preview
        id: application_preview
        uses: azure/bicep-deploy@v2
        with:
          type: deployment
          operation: whatIf
          name: application_preview-${{env.runNumber}}
          scope: resourceGroup
          subscription-id: ${{secrets.WL_OL1_SUB_ID}}
          resource-group-name: ${{ env.appRgName }}
          template-file: ./ALZ-Deploy/workloads/workload-online1/main.bicep
          parameters-file: ./ALZ-Deploy/workloads/workload-online1/parameters/workload-online1.parameters.${{inputs.environment}}.json
          parameters: |
            parVnetResourceId: '/subscriptions/${{secrets.WL_OL1_SUB_ID}}/resourceGroups/${{inputs.vnetrg}}/providers/Microsoft.Network/virtualNetworks/${{inputs.vnetrg}}'
  wl_ol1_app_deploy:
    runs-on: ubuntu-latest
    needs: wl_ol1_app_validation_preview
    if: ${{ inputs.deploy == true }}
    environment: ${{inputs.environment}}
    name: WL-OL1 Application - Deploy
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          path: 'ALZ-Deploy'
      - name: Checkout Repo bicep-registry-modules
        uses: actions/checkout@v4
        with:
            repository: Azure/bicep-registry-modules
            path: 'bicep-registry-modules'
      - name: Show env
        run: env | sort
      - name: Azure Login with OIDC
        uses: azure/login@v2
        with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Application - Deploy
        id: application_deploy
        uses: azure/bicep-deploy@v2
        with:
          type: deployment
          operation: create
          name: application_deploy-${{env.runNumber}}
          scope: resourceGroup
          subscription-id: ${{secrets.WL_OL1_SUB_ID}}
          resource-group-name: ${{ env.appRgName }}
          template-file: ./ALZ-Deploy/workloads/workload-online1/main.bicep
          parameters-file: ./ALZ-Deploy/workloads/workload-online1/parameters/workload-online1.parameters.${{inputs.environment}}.json
          parameters: |
            parVnetResourceId: '/subscriptions/${{secrets.WL_OL1_SUB_ID}}/resourceGroups/${{inputs.vnetrg}}/providers/Microsoft.Network/virtualNetworks/${{inputs.vnetrg}}'
      - name: Disable function app authentication
        id: fix_function_auth
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account set -s "${{secrets.WL_OL1_SUB_ID}}"
            az config set extension.use_dynamic_install=yes_without_prompt
            az extension add --name authV2  
            az webapp auth update -n ${{steps.application_deploy.outputs.acmeBotAppName}} -g ${{ env.appRgName }} --enabled false
            echo "functionAppKey: ${{steps.application_deploy.outputs.outFunctionAppKey}}"
            functionAppKey=$(az functionapp keys list -n ${{steps.application_deploy.outputs.acmeBotAppName}} -g ${{ env.appRgName }} --query functionKeys.default --output tsv)

