name: 1. Wipe ALZ Base Components 

on:
  workflow_dispatch:
    inputs:
      environment:
        default: "canary"
        required: true
        type: string
      alzBicepRelease:
        default: "v0.19.4"
        required: true
        type: string
      managementGroupPrefix:
        default: "alz"
        required: true
        type: string

  workflow_call:
    inputs:
      environment:
        default: "canary"
        required: true
        type: string
      alzBicepRelease:
        default: "v0.19.4"
        required: true
        type: string
      managementGroupPrefix:
        default: "alz"
        required: true
        type: string
    secrets:
      AZURE_CLIENT_ID:
        required: false
      AZURE_TENANT_ID:
        required: false
      AZURE_SUBSCRIPTION_ID:
        required: false

env:
  alzBicepRelease: ${{inputs.alzBicepRelease}}
  ManagementGroupPrefix: ${{inputs.managementGroupPrefix}}
  ManagementGroupSuffix: "-${{inputs.environment}}"
  runNumber: ${{ github.run_number }}

permissions:
  id-token: write
  contents: read

jobs:
  wipe:
    runs-on: ubuntu-latest
    environment: wipe
    steps:
      - run: echo "Here is where you'd perform the steps to wipe."
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Checkout ALZ-Bicep Repo
        uses: actions/checkout@v4
        with:
          repository: Azure/ALZ-Bicep
          path: ALZ-Bicep
          ref: ${{ env.alzBicepRelease }}
      - name: Show env
        run: env | sort
      - name: Azure Login with OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Cleaning up ALZ deployments
        uses: azure/powershell@v2
        with:
          inlineScript: | 
            ./scripts/Wipe-ESLZAzTenantUnattended.ps1 -tenantRootGroupID ${{ secrets.AZURE_TENANT_ID }} -intermediateRootGroupID "${{ env.ManagementGroupPrefix}}${{ env.ManagementGroupSuffix}}" -resetMdfcTierOnSubs:$true
          azPSVersion: "latest" 
