name: 89. Wipe Onpremise Network Infrastructure

on:
  workflow_dispatch:
    inputs:
      environment:
        default: "canary"
        required: true
        type: string
      

  workflow_call:
    inputs:
      environment:
        default: "canary"
        required: true
        type: string
    secrets:
      ONPREM_SUB_ID:
        required: false
      AZURE_CLIENT_ID:
        required: false
      AZURE_TENANT_ID:
        required: false
      AZURE_SUBSCRIPTION_ID:
        required: false
      CONNECTIVITY_SUB_ID:
        required: false

env:
  ManagementGroupSuffix: "-${{inputs.environment}}"
  onpremSubscriptionId: ${{secrets.ONPREM_SUB_ID}}
  ConnectivitySubId: ${{ secrets.CONNECTIVITY_SUB_ID }}
  onpremResourceGroupName: "rg-${{inputs.environment}}-onprem"
  runNumber: ${{ github.run_number }}

permissions:
  id-token: write
  contents: read

jobs:
  wipe:
    runs-on: ubuntu-latest
    environment: wipe
    name: Cleaning up onprem environment
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Show env
        run: env | sort
      - name: Azure Login with OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true
      - name: Cleaning up onprem subscription
        uses: azure/powershell@v2
        with:
          inlineScript: | 
            ./scripts/Wipe-Subscription.ps1 -subscriptionId ${{ env.onpremSubscriptionId }} -resetMdfcTierOnSubs:$true
          azPSVersion: "latest" 